---
title: "Preliminary report of the Final Paper"
subtitle: "for the CEU MSc in Business Analytics program"
author: "Gabor Horvath"
output: 
  pdf_document:
    number_sections: true
description: "This contains the description of the business needs and the scope of the project, results of the analysis with exhibits, and recommendations for management."
header-includes:
  - \usepackage{color}
---
\pagenumbering{gobble}
\newpage
\pagenumbering{arabic}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 1. Business understanding

Determine Business Objectives
Background
<Record the information that is known about the organization’s business situation at the beginning of the project.> - N/A
Business Objectives
Business Success Criteria
Identification of featured determining the risk potential of an airport
Working model for animal strike prediction
Assess Situation
Inventory of resources
Flight Data
Animal Strike Data
R
Buckets
Requirements, Assumptions, and Constraints
Risks and Contingencies
No initial Risks identified
No initial Contingencies identified
Terminology
Costs and Benefits
This is a one-man project, no significant cost is expected. Main benefit is to put to and almost E2E scenario the topics covered during the courses and discovering bits and bolts of the techniques for creating the project. 
Determine Data Mining Goals
Data Mining Goals
Understand, Analyse, Clean and Merge the source data correctly
Create the required attributes
Generate the required records (if applicable)
Data Mining Success Criteria
Identification of featured determining the risk potential of an airport
Working model for animal strike prediction
Produce Project Plan
Project Plan
<Legyen csak egy initial task lista az SPSS assessment + CEU elvárások alapján>
<Ez legyen a buckets link mint task kezelő>
Initial Assessment of Tools and Techniques
<Ezt ki lehet venni a 01-es dokumentumból, ott már van eg rendes felsorolás.>

II. Data Understanding
Collect Initial Data
Initial Data Collection Report
Describe Data
Data Description Report
Explore Data
Data Exploration Report
Verify Data Quality
Data Quality Report


III. Data Preparation
Data Set
Data Set Description
Select Data
Rationale for Inclusion / Exclusion
Clean Data
Data Cleaning Report
Construct Data
Derived Attributes
Generated Records
Integrate Data
Merged Data
Format Data
Reformatted Data


IV. Modelling
Select Modelling Technique
Modelling Technique
Modelling Assumptions
Generate Test Design
Test Design
Build Model
Parameter Settings
Models
Model Descriptions
Assess Model
Model Assessment
Revised Parameter Settings

V. Evaluation
Evaluate Results
Assessment of Data Mining Result w.r.t. Business Success Criteria
Approved Models
Review Process
Review of Process
Determine Next Steps
List of Possible Actions
Decisions

VI. Deployment
Plan Deployment
Deployment plan
Plan Monitoring and Maintenance
Monitoring and Maintenance Plan
Produce Final Report
Final Report
Final Presentation
Review Project
Experience Documentation



# 3. Contributors

Student: Gabor Horvath  
Mentor: Gergely Daroczi