---
output:
  pdf_document:
    latex_engine: xelatex
    number_sections: true
---

### Data Quality Report


#### Animal Strike Data

The data set provided by the Federal Aviation Administration is a data set based on voluntary strike reporting from airlines, airports, pilots, and other sources. Therefore the quality of the data enormously depends on the goodwill of the reporting source and even with the best intentions there are several quality issues which needs to be addressed later in the project.

* Mixed use of uppercase and lowercase letters/codes
* Mixed use of codes (e.g.: engine type is defined as "A/C")
* Number of States in the data set is above the actual number of states of the U.S.

The Federal Aviation Administration provides code books for some of the data details in the strike reports. Based on these code books the records with the following values can be removed from the data set, as they are not relevant for the goals of the project.


| Column name | Value | Reason for removal                             |
|:------------|:------|:-----------------------------------------------|
|OPID|"PVT"|Record is related of a strike to a privately owned aircraft, not to an aircraft operated by a commercial airline.|
|OPID|"BUS"|Record is related of a strike to a business aircraft, not to an aircraft operated by a commercial airline.|
|OPID|"GOV"|Record is related of a strike to a government aircraft, not to an aircraft operated by a commercial airline.|
|OPID|"MIL"|Record is related of a strike to a military aircraft, not to an aircraft operated by a commercial airline.|
|OPID|"UNKC"|Record is related of a strike to an aircraft of an unknown commercial operator. Without this information identification of the flight can't be done correctly.|
|OPID|"UNK"|Record is related of a strike to an aircraft of an unknown operator. Without this information identification of the flight can't be done correctly.|
|AC_CLASS|"B"|Value stands for helicopter.|
|AC_CLASS|"C"|Value stands for glider.|
|AC_CLASS|"D"|Value stands for balloon.|
|AC_CLASS|"F"|Value stands for dirigible.|
|AC_CLASS|"I"|Value stands for gyroplane.|
|AC_CLASS|"J"|Value stands for ultralight.|
|AC_CLASS|"Y"|Value stands for other.|
|AC_CLASS|"Z"|Value stands for unknown.|
|AC_CLASS|""|Value is empty.|
|TYPE_ENG|"E"|Value stands for none (glider).|
|TYPE_ENG|"F"|Value stands for turboshaft (helicopter).|
|TYPE_ENG|""|Value is empty.|


The strike report itself contains a great deal of details, which can be used in different projects, but for my purposes the following details have to be removed to concentrate on those information, which I expect to be the cause and not the effect of the strike. The following details needs to be removed from the data set in a later stage.

| Column name         | Explanation of Column Name and Codes          |
|:--------------------|:----------------------------------------------|
|AMA|International Civil Aviation Organization code for Aircraft Make|
|AMO|International Civil Aviation Organization code for Aircraft Model |
|EMA|Engine Make Code|
|EMO|Engine Model Code|
|NUM_ENGS|Number of engines|
|ENG_1_POS|Where engine # 1 is mounted  on aircraft|
|ENG_2_POS|Where engine # 2 is mounted  on aircraft|
|ENG_3_POS|Where engine # 3 is mounted  on aircraft|
|ENG_4_POS|Where engine # 4 is mounted  on aircraft|
|REMAINS_COLLECTED|Indicates if bird or wildlife remains were found and collected|
|REMAINS_SENT|Indicates if remains were sent to the Smithsonian Institution for identification|
|LOCATION|Various information about aircraft location if enroute or airport where strike evidence was found. Some locations show the two airports for the flight departure and arrival if pilot was unaware of the strike.|
|DAMAGE|Amount of the damage.|
|STR_RAD|Struck radome|
|DAM_RAD|Damaged radome|
|STR_WINDSHLD|Struck windshield|
|DAM_WINDSHLD|Damaged windshield|
|STR_NOSE|Struck nose|
|DAM_NOSE|Damaged nose|
|STR_ENG1|Struck Engine 1|
|DAM_ENG1|Damaged Engine 1|
|STR_ENG2|Struck Engine 2|
|DAM_ENG2|Damaged Engine 2|
|STR_ENG3|Struck Engine 3|
|DAM_ENG3|Damaged Engine 3|
|STR_ENG4|Struck Engine 4|
|DAM_ENG4|Damaged Engine 4|
|INGESTED|Engine ingested the bird/ animal|
|STR_PROP|Struck Propeller|
|DAM_PROP|Damaged Propeller|
|STR_WING_ROT|Struck Wing or Rotor|
|DAM_WING_ROT|Damaged Wing or Rotor|
|STR_FUSE|Struck Fuselage|
|DAM_FUSE|Damaged Fuselage|
|STR_LG|Struck Landing Gear|
|DAM_LG|Damaged Landing Gear|
|STR_TAIL|Struck Tail|
|DAM_TAIL|Damaged Tail|
|STR_LGHTS|Struck Lights|
|DAM_LGHTS|Damaged Lights|
|STR_OTHER|Struck Other than parts shown above|
|DAM_OTHER|Damaged Other than parts shown above|
|OTHER_SPECIFY|What part was struck other than those listed above|
|EFFECT|Effect on flight|
|EFFECT_OTHER|Effect on flight other than those listed on the form|
|SPECIES_ID|International Civil Aviation Organization code for type of bird or other wildlife|
|SPECIES|Common name for bird or other wildlife|
|BIRDS_SEEN|Number of birds/wildlife seen by pilot|
|BIRDS_STRUCK|Number of birds/wildlife struck|
|SIZE|Size of bird as reported by pilot is a relative scale. Entry should reflect the perceived size as opposed to a scientifically determined value. If more than one species was struck, larger bird is entered.|
|COMMENTS|As entered by database manager. Can include name of aircraft owner, types of reports received, updates, etc.|
|REMARKS|Most of remarks are from the form but some are data entry notes and are usually in parentheses.|
|AOS|Time aircraft was out of service in hours. If unknown, it is blank.|
|COST_REPAIRS|Estimated cost of repairs of replacement in dollars (USD)|
|COST_OTHER|Estimated other costs, other than those in previous field in dollars (USD). May include loss of revenue, hotel expenses due to flight cancellation, costs of fuel dumped, etc.|
|COST_REPAIRS_INFL_ADJ|Costs adjusted for inflation|
|COST_OTHER_INFL_ADJ|Other cost adjusted for inflation|
|REPORTED_NAME|Name(s) of person(s) filing report|
|REPORTED_TITLE|Title(s) of person(s) filing report|
|REPORTED_DATE|Date report was written|
|SOURCE|Type of report. Note: for multiple types of reports this will be indicated as Multiple.  See "Comments" field for details|
|PERSON|Only one selection allowed. For multiple reports, see field "Reported Title"|
|NR_INJURIES|Number of people injured|
|NR_FATALITIES|Number of human fatalities|
|LUPDATE|Last time record was updated|
|TRANSFER|Unused field at this time|
|INDICATED_DAMAGE|Indicates whether or not aircraft was damaged|


#### Flight Data

The data set provided by the United States Department of Transportation is a data set based on the timetable and the actual flight information collected by various systems. Therefore the quality of the data is significantly better than the data from the Federal Aviation Administration Animal Strike Database, but there are still some possible quality issues which needs to be addressed later in the project after further investigation. These issues include:

* Number of States in the data set is above the actual number of states of the U.S.

The data in the Federal Aviation Administration Animal Strike Database is available only until 30-4-2016, so the flight data needs to be adjusted accordingly.

Similarly to the Federal Aviation Administration Animal Strike Database, the flight performance data set contains a great deal of details as well, which can be used in different projects, but for my purposes the following details have to be removed to concentrate on those information, which I expect to be the cause and not the effect of the strike. The following details needs to be removed from the data set in a later stage.

| Column name     | Explanation of Column Name and Codes              |
|:----------------|:--------------------------------------------------|
|UniqueCarrier|Unique Carrier Code. When the same code has been used by multiple carriers, a numeric suffix is used for earlier users, for example, PA, PA(1), PA(2). Use this field for analysis across a range of years.|
|AirlineID|An identification number assigned by US DOT to identify a unique airline (carrier). A unique airline (carrier) is defined as one holding and reporting under the same DOT certificate regardless of its Code, Name, or holding company/corporation.|
|TailNum|Tail Number|
|OriginAirportID|Origin Airport, Airport ID. An identification number assigned by US DOT to identify a unique airport. Use this field for airport analysis across a range of years because an airport can change its airport code and airport codes can be reused.|
|OriginAirportSeqID|Origin Airport, Airport Sequence ID. An identification number assigned by US DOT to identify a unique airport at a given point of time. Airport attributes, such as airport name or coordinates, may change over time.|
|OriginCityMarketID|Origin Airport, City Market ID. City Market ID is an identification number assigned by US DOT to identify a city market. Use this field to consolidate airports serving the same city market.|
|OriginStateFips|Origin Airport, State Fips|
|OriginWac|Origin Airport, World Area Code|
|DestAirportID|Destination Airport, Airport ID. An identification number assigned by US DOT to identify a unique airport. Use this field for airport analysis across a range of years because an airport can change its airport code and airport codes can be reused.|
|DestAirportSeqID|Destination Airport, Airport Sequence ID. An identification number assigned by US DOT to identify a unique airport at a given point of time. Airport attributes, such as airport name or coordinates, may change over time.|
|DestCityMarketID|Destination Airport, City Market ID. City Market ID is an identification number assigned by US DOT to identify a city market. Use this field to consolidate airports serving the same city market.|
|DestStateFips|Destination Airport, State Fips|
|DestWac|Destination Airport, World Area Code|
|CRSDepTime|CRS Departure Time (local time: hhmm)|
|DepTime|Actual Departure Time (local time: hhmm)|
|DepDelay|Difference in minutes between scheduled and actual departure time. Early departures show negative numbers.|
|DepDelayMinutes|Difference in minutes between scheduled and actual departure time. Early departures set to 0.|
|DepDel15|Departure Delay Indicator, 15 Minutes or More (1=Yes)|
|DepartureDelayGroups|Departure Delay intervals, every (15 minutes from <-15 to >180)|
|TaxiOut|Taxi Out Time, in Minutes|
|WheelsOff|Wheels Off Time (local time: hhmm)|
|WheelsOn|Wheels On Time (local time: hhmm)|
|TaxiIn|Taxi In Time, in Minutes|
|ArrTime|Actual Arrival Time (local time: hhmm)|
|ArrDelay|Difference in minutes between scheduled and actual arrival time. Early arrivals show negative numbers.|
|ArrDelayMinutes|Difference in minutes between scheduled and actual arrival time. Early arrivals set to 0.|
|ArrDel15|Arrival Delay Indicator, 15 Minutes or More (1=Yes)|
|ArrivalDelayGroups|Arrival Delay intervals, every (15-minutes from <-15 to >180)|
|Cancelled|Cancelled Flight Indicator (1=Yes)|
|CancellationCode|Specifies The Reason For Cancellation|
|Diverted|Diverted Flight Indicator (1=Yes)|
|ActualElapsedTime|Elapsed Time of Flight, in Minutes|
|AirTime|Flight Time, in Minutes|
|Flights|Number of Flights|
|CarrierDelay|Carrier Delay, in Minutes|
|WeatherDelay|Weather Delay, in Minutes|
|NASDelay|National Air System Delay, in Minutes|
|SecurityDelay|Security Delay, in Minutes|
|LateAircraftDelay|Late Aircraft Delay, in Minutes|
|FirstDepTime|First Gate Departure Time at Origin Airport|
|TotalAddGTime|Total Ground Time Away from Gate for Gate Return or Cancelled Flight|
|LongestAddGTime|Longest Time Away from Gate for Gate Return or Cancelled Flight|
|DivAirportLandings|Number of Diverted Airport Landings|
|DivReachedDest|Diverted Flight Reaching Scheduled Destination Indicator (1=Yes)|
|DivActualElapsedTime|Elapsed Time of Diverted Flight Reaching Scheduled Destination, in Minutes. The ActualElapsedTime column remains NULL for all diverted flights.|
|DivArrDelay|Difference in minutes between scheduled and actual arrival time for a diverted flight reaching scheduled destination. The ArrDelay column remains NULL for all diverted flights.|
|DivDistance|Distance between scheduled destination and final diverted airport (miles). Value will be 0 for diverted flight reaching scheduled destination.|
|Div1Airport|Diverted Airport Code1|
|Div1AirportID|Airport ID of Diverted Airport 1. Airport ID is a Unique Key for an Airport|
|Div1AirportSeqID|Airport Sequence ID of Diverted Airport 1. Unique Key for Time Specific Information for an Airport|
|Div1WheelsOn|Wheels On Time (local time: hhmm) at Diverted Airport Code1|
|Div1TotalGTime|Total Ground Time Away from Gate at Diverted Airport Code1|
|Div1LongestGTime|Longest Ground Time Away from Gate at Diverted Airport Code1|
|Div1WheelsOff|Wheels Off Time (local time: hhmm) at Diverted Airport Code1|
|Div1TailNum|Aircraft Tail Number for Diverted Airport Code1|
|Div2Airport|Diverted Airport Code2|
|Div2AirportID|Airport ID of Diverted Airport 2. Airport ID is a Unique Key for an Airport|
|Div2AirportSeqID|Airport Sequence ID of Diverted Airport 2. Unique Key for Time Specific Information for an Airport|
|Div2WheelsOn|Wheels On Time (local time: hhmm) at Diverted Airport Code2|
|Div2TotalGTime|Total Ground Time Away from Gate at Diverted Airport Code2|
|Div2LongestGTime|Longest Ground Time Away from Gate at Diverted Airport Code2|
|Div2WheelsOff|Wheels Off Time (local time: hhmm) at Diverted Airport Code2|
|Div2TailNum|Aircraft Tail Number for Diverted Airport Code2|
|Div3Airport|Diverted Airport Code3|
|Div3AirportID|Airport ID of Diverted Airport 3. Airport ID is a Unique Key for an Airport|
|Div3AirportSeqID|Airport Sequence ID of Diverted Airport 3. Unique Key for Time Specific Information for an Airport|
|Div3WheelsOn|Wheels On Time (local time: hhmm) at Diverted Airport Code3|
|Div3TotalGTime|Total Ground Time Away from Gate at Diverted Airport Code3|
|Div3LongestGTime|Longest Ground Time Away from Gate at Diverted Airport Code3|
|Div3WheelsOff|Wheels Off Time (local time: hhmm) at Diverted Airport Code3|
|Div3TailNum|Aircraft Tail Number for Diverted Airport Code3|
|Div4Airport|Diverted Airport Code4|
|Div4AirportID|Airport ID of Diverted Airport 4. Airport ID is a Unique Key for an Airport|
|Div4AirportSeqID|Airport Sequence ID of Diverted Airport 4. Unique Key for Time Specific Information for an Airport|
|Div4WheelsOn|Wheels On Time (local time: hhmm) at Diverted Airport Code4|
|Div4TotalGTime|Total Ground Time Away from Gate at Diverted Airport Code4|
|Div4LongestGTime|Longest Ground Time Away from Gate at Diverted Airport Code4|
|Div4WheelsOff|Wheels Off Time (local time: hhmm) at Diverted Airport Code4|
|Div4TailNum|Aircraft Tail Number for Diverted Airport Code4|
|Div5Airport|Diverted Airport Code5|
|Div5AirportID|Airport ID of Diverted Airport 5. Airport ID is a Unique Key for an Airport|
|Div5AirportSeqID|Airport Sequence ID of Diverted Airport 5. Unique Key for Time Specific Information for an Airport|
|Div5WheelsOn|Wheels On Time (local time: hhmm) at Diverted Airport Code5|
|Div5TotalGTime|Total Ground Time Away from Gate at Diverted Airport Code5|
|Div5LongestGTime|Longest Ground Time Away from Gate at Diverted Airport Code5|
|Div5WheelsOff|Wheels Off Time (local time: hhmm) at Diverted Airport Code5|
|Div5TailNum|Aircraft Tail Number for Diverted Airport Code5|

#### Airport Data

The data set provided by the Federal Aviation Administration is a data set created based on the Airport Master Record (5010-*) forms. The following list of issues needs to be corrected in a later stage of the project:

* The LocationID have an apostrophe as the first character, which should be removed for further processing.
* Number of States in the data set is above the actual number of states of the U.S.

The Federal Aviation Administration provides code books for some of the data details in the airport data. Based on these code books the records with the following values can be removed from the data set, as they are not relevant for the goals of the project.

| Column name | Value      | Reason for removal                        |
|:------------|:-----------|:------------------------------------------|
|TYPE|"BALLOONPORT"|Record is indicating a balloon port, not an airport.|
|TYPE|"GLIDERPORT"|Record is indicating a glider port, not an airport.|
|TYPE|"HELIPORT"|Record is indicating a helicopter port, not an airport.|
|TYPE|"SEAPLANE BASE"|Record is indicating a port for seaplanes, not an airport.|
|TYPE|"ULTRALIGHT"|Record is indicating a port for ultralight airplanes, not an airport.|

Similarly to the previous data sets this data set contains a great deal of details as well, which can be used in different projects, but for our purposes the following details have to be removed.

| Column name          | Explanation of Column Name and Codes         |
|:---------------------|:---------------------------------------------|
|SiteNumber|Landing facility site number - a unique identifying number which, together with the landing facility type code, forms the key to the airport record. (ex. 04508.*A)|
|EffectiveDate|Information effective date (mm/dd/yyyy). This date coincides with the 56-day charting and publication cycle date.|
|DistrictOffice|FAA district or field office code. (ex. CHI)|
|County|Associated county (or parish) name. (ex. Cook)|
|CountyState|Associated county's state (post office code) state where the associated county is located; may not be the same as the associated city's state code. (ex. IL)|
|Ownership|Airport ownership type. (ex. PU - publicly owned, PR - privately owned, MA - air force owned, MN - navy owned, MR - army owned)|
|Use|Facility use. (ex. PU - open to the public, PR - private)|
|Owner|Facility owner's name.|
|OwnerAddress|Owner's address.|
|OwnerCSZ|Owner's city, state and zip code.|
|OwnerPhone|Owner's phone number. (data formats: nnn-nnn-nnnn (area code + phone number), 1-nnn-nnnn (dial 1-800 then number), 8-nnn-nnnn (dial 800 then number)|
|Manager|Facility manager's name.|
|ManagerAddress|Manager's address.|
|ManagerCSZ|Manager's city, state and zip code.|
|ManagerPhone|Manager's phone number. (data formats: nnn-nnn-nnnn (area code + phone number), 1-nnn-nnnn (dial 1-800 then number), 8-nnn-nnnn (dial 800 then number)|
|ARPMethod|Airport reference point determination method. (ex. E - estimated, S - surveyed)|
|ARPElevationMethod|Airport elevation determination method. (ex. E - estimated, S - surveyed)|
|MagneticVariation|Magnetic variation and direction magnetic variation to nearest degree. (ex. 03W)|
|MagneticVariationYear|Magnetic variation epoch year. (ex. 1985)|
|TrafficPatternAltitude|Traffic pattern altitude (whole feet AGL). (ex. 1000)|
|ChartName|Aeronautical sectional chart on which facility appears. (ex. Washington)|
|DistanceFromCBD|Distance from central business district of the associated city to the airport (nearest nautical mile - ex. 08).|
|DirectionFromCBD|Direction of airport from central business district of associated city (nearest 1/8 compass point - ex. NE).|
|BoundaryARTCCID|Boundary ARTCC Identifier.  The boundary ARTCC is the FAA air route traffic control center within whose published boundaries the airport lies. It may not be the controlling ARTCC for the airport if a letter of agreement exists between the boundary ARTCC and another ARTCC. (ex. ZDC for Washington ARTCC)|
|BoundaryARTCCComputerID|Boundary ARTCC (FAA) computer identifier. (ex. ZCW for Washington ARTCC)|
|BoundaryARTCCName|Boundary ARTCC name. (ex. Washington)|
|ResponsibleARTCCID|Responsible ARTCC identifier the responsible ARTCC is the FAA air route traffic control center who has assumed control over the airport through a letter of agreement with the boundary ARTCC. (ex. ZDC for Washington ARTCC)|
|ResponsibleARTCCComputerID|Responsible ARTCC (FAA) computer identifier. (ex. ZCW for Washington ARTCC)|
|ResponsibleARTCCName|Responsible ARTCC name. (ex. Washington)|
|TieInFSS|Tie-in FSS physically located on facility. (ex. Y - tie-in FSS is on the airport, n - tie-in FSS is not on the airport)|
|TieInFSSID|Tie-in flight service station (FSS) identifier. (ex. DCA for Washington FSS)|
|TieInFSSName|Tie-in FSS name. (ex. Washington)|
|AirportToFSSPhoneNumber|Local phone number from airport to FSS for adminstrative services|
|TieInFSSTollFreeNumber|Toll free phone number from airport to FSS for pilot briefing services the data describes the type of toll-free communications and the number to dial. The data formats and their meanings are: 1-nnn-nnnn, dial 1-800- then nnn-nnnn; 8-nnn-nnnn, dial 800 then nnn-nnnn; e-nnnnnnnn, enterprise number dial 0 & ask for enterprise nnnnnnnn; lcnnn-nnnn, local call - dial nnn-nnnn; dl, direct line telephone at the airport - no dialing required; z-nnnnnnnn, zenith number - dial 0 and ask for zenith nnnnnnnn; w-nnnnnnnn, dial 0 and ask for wx nnnnnnnn; c-nnnnnnnn, dial 0 and ask for commerce nnnnnnnn; ld-nnnnnnnn, long distance call - dial (area code) then nnnnnnn; lt-nnnnnnnn, long distal call dial 1-nnnnnnn; 1-wx-brief, dial 1-800-wx-brief; 8-wx-brief, dial 800-wx-brief|
|AlternateFSSID|Alternate FSS identifier provides the identifier of a full-time flight service station that assumes responsibility for the airport during the off hours of a part-time primary FSS. (ex. 'DCA' for Washington FSS)|
|AlternateFSSName|Alternate FSS name. (ex. 'Washington' for Washington FSS)|
|AlternateFSSTollFreeNumber|Toll free phone number from airport to FSS for pilot briefing services the data describes the type of toll-free communications and the number to dial. The data formats and their meanings are: 1-nnn-nnnn, dial 1-800- then nnn-nnnn; 8-nnn-nnnn, dial 800 then nnn-nnnn; e-nnnnnnnn, enterprise number dial 0 & ask for enterprise nnnnnnnn; lcnnn-nnnn, local call - dial nnn-nnnn; dl, direct line telephone at the airport - no dialing required; z-nnnnnnnn, zenith number - dial 0 and ask for zenith nnnnnnnn; w-nnnnnnnn, dial 0 and ask for wx nnnnnnnn; c-nnnnnnnn, dial 0 and ask for commerce nnnnnnnn; ld-nnnnnnnn, long distance call - dial (area code) then nnnnnnn; lt-nnnnnnnn, long distal call dial 1-nnnnnnn; 1-wx-brief, dial 1-800-wx-brief; 8-wx-brief, dial 800-wx-brief.|
|NOTAMFacilityID|Identifier of the facility responsible for issuing notices to airmen (NOTAMS) and weather information for the airport. (ex. ORD)|
|NOTAMService|Availability of NOTAM 'd' service at airport. (ex. Y - yes, N - no)|
|ActivationDate|Airport activation date (mm/yyyy). Provides the month and year that the facility was added to the NFDC airport database. Note: this information is only available for those facilities opened since 1981. (ex. 06/1981)|
|CertificationTypeDate|Airport certification type and date. Format is the class code ('I', 'II', 'III' or 'IV') followed by a one characther code A, B, C, D, E, or L, followed by a one character code S or U, followed by the month and year of certification. (ex. 'I A S 07/1980', 'I C S 01/1983' or 'I A U 09/1983').  Codes A, B, C, D, and E are for airports having a full certificate under CFR Part 139, and receiving scheduled air carrier service from carriers certificated by the Civil Aeronautics Board.  The A, B, C, D, and E identify the aircraft rescue and firefighting index for the airport.  Code L is for airports having limited certification under CFR Part 139.  Code S is for Airports receiving scheduled air carrier service from carriers certificated by the Civil Aeronautics Board.  Code U is for airports not receiving this scheduled service.|
|FederalAgreements|NPIAS/Federal Agreement Code.  A combination of 1 to 7 codes that indicate the type of federal agreements existing at the airport. (ex. NGH). N - national plan of integrated airport systems (NPIAS); B - installation of navigational facilities on privately owned airports under F&E program; G - grant agreements under FAAP/ADAP/AIP; H - compliance with accessibility to the handicapped; P - surplus property agreement under Public Law 289; R - surplus property agreement under Regulation 16-WAA; S - conveyance under section 16, Federal Airport Act of 1946 or Section 23, Airport and Airway Development Act of 1970; V - advance planning agreement under FAAP; X - obligations assumed by transfer; Y - assurances pursuant to Title VI, Civil Rights Act of 1964; Z - conveyance under Section 303(C), Federal Aviation Act of 1958; 1 - grant agreement has expired, however, agreement remains in effect for this facility as long as it is public use.|
|AirspaceDetermination|Airport airspace analysis determination. (ex. CONDL (conditional), NOT ANALYZED, NO OBJECTION, OBJECTIONABLE)|
|CustomsAirportOfEntry|Facility has been designated by the U.S. Treasury as an international airport of entry for customs (ex. Y - yes, N - no)|
|CustomsLandingRights|Facility has been designated by the U.S. Treasury as a customs landing rights airport (ex. Y - yes, N - no)|
|MilitaryJointUse|Facility has military/civil joint use agreement that allows civil operations at a military airport or military operations at a civil airport (ex. Y - yes, N - no)|
|MilitaryLandingRights|Airport has entered into an agreement that grants landing rights to the military (ex. Y - yes, N - no)|
|InspectionMethod|Airport inspection method. (ex. F - federal, S - state, C - contractor, 1 - 5010-1 public use mail out program, 2 - 5010-2 private use mail out program)|
|InspectionGroup|Agency/group performing physical inspection (ex. F - faa airports field personnel, s - state aeronautical personnel, c - private contract personnel, n - owner)|
|LastInspectionDate|Last physical inspection date (mmddyyyy)|
|LastOwnerInformationDate|Last date information request was completed by facility owner or manager (mmddyyyy)|
|FuelTypes|Fuel types available for public use at the airport. There can be up to 8 occurrences of a fixed 5 character field (ex. 80___100__100LL115__). 80 - grade 80 gasoline (red), 100 - grade 100 gasoline (green), 100LL - grade 100LL gasoline (low lead blue), 115 - grade 115 gasoline, A - jet A - kerosene, freeze point -40C, A1 - jet A-1 - kerosene, freeze point -50C, A1+ - jet A-1 - kerosene, with icing inhibitor freeze point -50C, B - jet B - wide-cut turbine fuel, freeze point -50C, B+ - jet B - wide-cut turbine fuel with icing inhibitor, freeze point -50C, MOGAS - automotive gasoline.|
|AirframeRepair|Airframe repair service availability/type. (ex. MAJOR, MINOR, NONE)|
|PowerPlantRepair|Power plant (engine) repair availability/type. (ex. MAJOR, MINOR, NONE)|
|BottledOxygenType|Type of bottled oxygen available (value represents high and/or low pressure replacement bottle). (ex. HIGH, LOW, HIGH/LOW, NONE)|
|BulkOxygenType|Type of bulk oxygen available (value represents high and/or low pressure cylinders). (ex. HIGH, LOW, HIGH/LOW, NONE)|
|LightingSchedule|Airport lighting schedule value is the beginning-ending times (local time) that lights are operated. Format can be 1900-2300, DUSK-0100, ALL, DUSK-DAWN, NONE, etc.|
|BeaconSchedule|Beacon lighting schedule value is the beginning-ending times (local time) that the rotating airport beacon light is operated. Value can be "SS-SR" (indicating sunset-sunrise), blank, or "SEE RMK", indicating that the details are in a facility remark data entry.|
|ATCT|Air traffic control tower located on airport. (ex. Y - yes, N - no)|
|UNICOMFrequencies|Unicom frequencies available at the airport there can be up to 6 occurrences of a fixed 7 character field. (ex. 122.700 or 122.700122.800 or NONE)|
|CTAFFrequency|Common traffic advisory frequency. (CTAF) (ex. 122.800)|
|SegmentedCircle|Segmented circle airport marker system on the airport. (ex. Y - yes, N - no, none)|
|BeaconColor|Lens color of operable beacon located on the airport. (ex. CG - clear-green (lighted land airport); CY - clear-yellow (lighted seaplane base); CGY - clear-green-yellow (heliport); SCG - split-clear-green (lighted military airport); C - clear (unlighted la|
|NonCommercialLandingFee|Landing fee charged to non-commercial users of airport. (ex. Y - yes, N - no)|
|MedicalUse|Landing facility is used for medical purposes. (ex. Y - yes, N - no)|
|SingleEngineGA|Number of single engine general aviation aircraft.|
|MultiEngineGA|Number of multi engine general aviation aircraft.|
|JetEngineGA|Number of jet engine general aviation aircraft.|
|HelicoptersGA|Number of general aviation helicopter.|
|GlidersOperational|Number of operational gliders.|
|MilitaryOperational|Number operational military aircraft (includingg helicopters).|
|Ultralights|Number of ultralight aircraft.|
|OperationsCommercial|Commercial services. Scheduled operations by cab-certificated carriers or intrastate carriers.|
|OperationsCommuter|Commuter services. Scheduled commuter and cargo carriers.|
|OperationsAirTaxi|Air taxi. Air taxi operators carrying passengers, mail, or mail for revenue.|
|OperationsGALocal|General aviation local operations. Those operating in the local traffic pattern or within a 20-mile radius of the airport.|
|OperationsGAItin|General aviation itinerant operations. Those general aviation operations (excluding commuter or air taxi) not qualifying as local.|
|OperationsMilitary|Military aircraft operations.|
|OperationsDate|12-month ending date on which annual operations data in above six field is based (mm/dd/yyyy).|
|AirportPositionSource|Airport position source.|
|AirportPositionSourceDate|Airport position source date (mm/dd/yyyy).|
|AirportElevationSource|Airport elevation source.|
|AirportElevationSourceDate|Airport elevation source date (mm/dd/yyyy).|
|ContractFuelAvailable|Contract fuel available. (ex. Y - yes, N - no)|
|TransientStorage|Transient storage. (ex. Y - yes, N - no, none)|
|OtherServices|Other services. (ex. Y - yes, N - no, none)|
|WindIndicator|Wind direction indicator. (ex. Y - yes, N - no, none)|

