---
output:
  pdf_document:
    latex_engine: xelatex
    number_sections: true
---

### Data Set Description

The resolution of the issues found during the data quality verification includes the reducing of several details originally provided by the Federal Aviation Administration and the United States Department of Transportation agencies. This section describes the resulted data sets.

#### Animal Strike Data

| Column name         | Explanation of Column Name and Codes          |
|:--------------------|:----------------------------------------------|
|INDEX NR|Individual record number|
|OPID|Airline operator code|
|OPERATOR|A three letter International Civil Aviation Organization code for aircraft operators. (BUS = business, PVT = private aircraft other than business, GOV = government aircraft, MIL - military aircraft.)|
|ATYPE|Aircraft|
|AC_CLASS|Type of aircraft (see Aircraft Type tab below)|
|AC_MASS|1 = 2,250 kg or less: 2 = ,2251-5700 kg: 3 = 5,701-27,000 kg: 4 = 27,001-272,000 kg: 5 = above 272,000 kg|
|TYPE_ENG|Type of power A = reciprocating engine (piston): B = Turbojet: C = Turboprop: D = Turbofan: E = None (glider): F = Turboshaft (helicopter): Y = Other|
|REG|Aircraft registration|
|FLT|Flight number|
|INCIDENT_DATE|Date strike occurred|
|INCIDENT_MONTH|Month strike occurred|
|INCIDENT_YEAR|Year strike occurred|
|TIME_OF_DAY|Light conditions|
|TIME|Hour and minute in local time|
|AIRPORT_ID|International Civil Aviation Organization airport identifier for location of strike whether it was on or off airport|
|AIRPORT|Name of airport|
|STATE|State|
|FAAREGION|FAA Region where airport is located|
|ENROUTE|If strike did not occur on approach, climb, landing roll, taxi or take-off, aircraft was enroute. This shows location.|
|RUNWAY|Runway|
|HEIGHT|Feet Above Ground Level|
|SPEED|Knots (indicated air speed)|
|DISTANCE|Miles from airport|
|PHASE_OF_FLT|Phase of flight during which strike occurred|
|SKY|Type of cloud cover, if any|
|PRECIP|Precipitation|
|WARNED|Pilot warned of birds/wildlife|

The number of details (columns) for each strike report has been reduces from 94 to 27.


#### Flight Data

| Column name     | Explanation of Column Name and Codes              |
|:----------------|:--------------------------------------------------|
|Year|Year|
|Quarter|Quarter (1-4)|
|Month|Month|
|DayofMonth|Day of Month|
|DayOfWeek|Day of Week|
|FlightDate|Flight Date (yyyymmdd)|
|Carrier|Code assigned by IATA and commonly used to identify a carrier. As the same code may have been assigned to different carriers over time, the code is not always unique. For analysis, use the Unique Carrier Code.|
|FlightNum|Flight Number|
|Origin|Origin Airport|
|OriginCityName|Origin Airport, City Name|
|OriginState|Origin Airport, State Code|
|OriginStateName|Origin Airport, State Name|
|Dest|Destination Airport|
|DestCityName|Destination Airport, City Name|
|DestState|Destination Airport, State Code|
|DestStateName|Destination Airport, State Name|
|CRSDepTime|CRS Departure Time (local time: hhmm)|
|DepTimeBlk|CRS Departure Time Block, Hourly Intervals|
|CRSArrTime|CRS Arrival Time (local time: hhmm)|
|CRSElapsedTime|CRS Elapsed Time of Flight, in Minutes|
|Distance|Distance between airports (miles)|
|DistanceGroup|Distance Intervals, every 250 Miles, for Flight Segment|

The number of details (columns) for each flight performance record has been reduces from 110 to 23.

#### Aiport Data

| Column name          | Explanation of Column Name and Codes         |
|:---------------------|:---------------------------------------------|
|Type|Landing facility type. (ex. Airport, Balloonport, Seaplane Base, Gliderport, Heliport, Stolport, Ultralight)|
|LocationID|Location identifier unique 3-4 character alphanumeric identifier assigned to the landing facility. (ex. 'ORD' for Chicago O'Hare)|
|Region|FAA region code. (ex. AAL - Alaska, ACE - Central, AEA - Eastern, AGL - Great Lakes, AIN - International, ANE - New England, ANM - Northwest Mountain, ASO - Southern, ASW - Southwest, AWP - Western-Pacific)|
|State|Associated state post office code standard two letter abbreviation for u.s. states and territories. (ex. IL, PR, CQ)|
|StateName|Associated state name. (ex. Illinois)|
|City|Associated city name. (ex. Chicago)|
|FacilityName|Official facility name. (ex. Chicago O'Hare Intl)|
|ARPLatitude|Airport reference point latitude (formatted).|
|ARPLatitudeS|Airport reference point latitude (seconds).|
|ARPLongitude|Airport reference point longitude (formatted).|
|ARPLongitudeS|Airport reference point longitude (seconds).|
|AirportStatusCode|Airport status code: CI - closed indefinitely; CP - closed permanently; O - operational|
|IcaoIdentifier|International coding for airport.|

The number of details (columns) for each airport record has been reduces from 102 to 8.
