---
output: 
  pdf_document:
    latex_engine: xelatex
    number_sections: true
    toc_depth: 4
#    pandoc_args: ["--output=Output/04-PreliminaryReport.pdf"]
urlcolor: blue
linkcolor: black
header-includes:
  - \usepackage{color}
  - \usepackage{fancyhdr}
  - \usepackage{multicol}    
mainfont: Times New Roman
monofont: Times New Roman
sansfont: Times New Roman
bibliography: 850-Bibliography.bib
---

```{r 940-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment=NA)
source("../90-UserDefinedFunctions.R")
suppressPackageStartupMessages(loadLibraries())
suppressPackageStartupMessages(readConfigFile(FALSE))
```

\pagenumbering{gobble}

```{r child = '941-TitlePage.Rmd'}
```

\newpage

\pagenumbering{arabic}
\pagestyle{fancy}
\fancyhf{}
\fancyfoot[C]{\thepage}
\renewcommand{\footrulewidth}{0.4pt}

# Introduction

```{r child = '010-Introduction.Rmd'}
```

\newpage

# Business Understanding

```{r child = '110-BusinessUnderstanding.Rmd'}
```

\newpage

# Data Understanding

```{r child = '210-DataUnderstanding.Rmd'}
```

\newpage

# Data Preparation

```{r child = '310-DataPreparation.Rmd'}
```

\newpage

# Modeling

```{r child = '410-Modeling.Rmd'}
```

\newpage

# Evaluation

```{r child = '510-Evaluation.Rmd'}
```


\newpage

# Contributors

```{r child = '860-Contributors.Rmd'}
```

\newpage

#Environment

```{r child = '870-Environment.Rmd'}
```

\newpage

```{r child = '880-TOC.Rmd'}
```

\newpage

#References

```{r child = '890-References.Rmd'}
```
