#setting the download parameters
URL <- getWData()
destfile <- paste(getDataDir(), "wildlife.zip", sep = "/")

method="auto"

#if the file exists then do not download again
if (file.exists(destfile) != TRUE)
{
  download.file(URL, destfile, method)
} else
{
  message("File exists no download required.")
}

destdir <- getDataDir()

#unzip the file
unzip(destfile, exdir = destdir)

#Convert Access database tables to csv files using the access2csv from "https://github.com/AccelerationNet/access2csv"

csvfile <- paste(destdir, "/STRIKE_REPORTS (1990-1999).csv", sep="")

if (file.exists(csvfile) != TRUE)
{
  setwd(getDataDir())
  system(paste("java -jar ", getDataDir(), "/access2csv.jar ", getDataDir(), "/wildlife.accdb", sep = ""))
  setwd(getMainDir())
  #dataFiles <- list.files(getMainDir(), "\\.csv",full.names = TRUE)
  #file.copy(dataFiles, getDataDir(), overwrite = TRUE)
  #file.remove(dataFiles)
} else
{
  message("File exists no extract required.")
}


#Read files to data frames --> data tables
sr_1990_1999 <- data.table(read.csv(paste(destdir,"/STRIKE_REPORTS (1990-1999).csv",sep=""), header = FALSE))
sr_2000_2009 <- data.table(read.csv(paste(destdir,"/STRIKE_REPORTS (2000-2009).csv",sep=""), header = FALSE))
sr_2010_Current <- data.table(read.csv(paste(destdir,"/STRIKE_REPORTS (2010-Current).csv",sep=""), header = FALSE))
#STRIKE_REPORTS_BASH --> only military, not required
#srb_1990_Current <- data.table(read.csv(paste(destdir,"/STRIKE_REPORTS_BASH (1990-Current).csv",sep=""), header = FALSE))

#Rename columns
names(sr_1990_1999) <- c("INDEX_NR","OPID","OPERATOR","ATYPE","AMA","AMO","EMA","EMO","AC_CLASS","AC_MASS","NUM_ENGS","TYPE_ENG","ENG_1_POS","ENG_2_POS","ENG_3_POS","ENG_4_POS","REG","FLT","REMAINS_COLLECTED","REMAINS_SENT","INCIDENT_DATE","INCIDENT_MONTH","INCIDENT_YEAR","TIME_OF_DAY","TIME","AIRPORT_ID","AIRPORT","STATE","FAAREGION","ENROUTE","RUNWAY","LOCATION","HEIGHT","SPEED","DISTANCE","PHASE_OF_FLT","DAMAGE","STR_RAD","DAM_RAD","STR_WINDSHLD","DAM_WINDSHLD","STR_NOSE","DAM_NOSE","STR_ENG1","DAM_ENG1","STR_ENG2","DAM_ENG2","STR_ENG3","DAM_ENG3","STR_ENG4","DAM_ENG4","INGESTED","STR_PROP","DAM_PROP","STR_WING_ROT","DAM_WING_ROT","STR_FUSE","DAM_FUSE","STR_LG","DAM_LG","STR_TAIL","DAM_TAIL","STR_LGHTS","DAM_LGHTS","STR_OTHER","DAM_OTHER","OTHER_SPECIFY","EFFECT","EFFECT_OTHER","SKY","PRECIP","SPECIES_ID","SPECIES","BIRDS_SEEN","BIRDS_STRUCK","SIZE","WARNED","COMMENTS","REMARKS","AOS","COST_REPAIRS","COST_OTHER","COST_REPAIRS_INFL_ADJ","COST_OTHER_INFL_ADJ","REPORTED_NAME","REPORTED_TITLE","REPORTED_DATE","SOURCE","PERSON","NR_INJURIES","NR_FATALITIES","LUPDATE","TRANSFER","INDICATED_DAMAGE")
names(sr_2000_2009) <- c("INDEX_NR","OPID","OPERATOR","ATYPE","AMA","AMO","EMA","EMO","AC_CLASS","AC_MASS","NUM_ENGS","TYPE_ENG","ENG_1_POS","ENG_2_POS","ENG_3_POS","ENG_4_POS","REG","FLT","REMAINS_COLLECTED","REMAINS_SENT","INCIDENT_DATE","INCIDENT_MONTH","INCIDENT_YEAR","TIME_OF_DAY","TIME","AIRPORT_ID","AIRPORT","STATE","FAAREGION","ENROUTE","RUNWAY","LOCATION","HEIGHT","SPEED","DISTANCE","PHASE_OF_FLT","DAMAGE","STR_RAD","DAM_RAD","STR_WINDSHLD","DAM_WINDSHLD","STR_NOSE","DAM_NOSE","STR_ENG1","DAM_ENG1","STR_ENG2","DAM_ENG2","STR_ENG3","DAM_ENG3","STR_ENG4","DAM_ENG4","INGESTED","STR_PROP","DAM_PROP","STR_WING_ROT","DAM_WING_ROT","STR_FUSE","DAM_FUSE","STR_LG","DAM_LG","STR_TAIL","DAM_TAIL","STR_LGHTS","DAM_LGHTS","STR_OTHER","DAM_OTHER","OTHER_SPECIFY","EFFECT","EFFECT_OTHER","SKY","PRECIP","SPECIES_ID","SPECIES","BIRDS_SEEN","BIRDS_STRUCK","SIZE","WARNED","COMMENTS","REMARKS","AOS","COST_REPAIRS","COST_OTHER","COST_REPAIRS_INFL_ADJ","COST_OTHER_INFL_ADJ","REPORTED_NAME","REPORTED_TITLE","REPORTED_DATE","SOURCE","PERSON","NR_INJURIES","NR_FATALITIES","LUPDATE","TRANSFER","INDICATED_DAMAGE")
names(sr_2010_Current) <- c("INDEX_NR","OPID","OPERATOR","ATYPE","AMA","AMO","EMA","EMO","AC_CLASS","AC_MASS","NUM_ENGS","TYPE_ENG","ENG_1_POS","ENG_2_POS","ENG_3_POS","ENG_4_POS","REG","FLT","REMAINS_COLLECTED","REMAINS_SENT","INCIDENT_DATE","INCIDENT_MONTH","INCIDENT_YEAR","TIME_OF_DAY","TIME","AIRPORT_ID","AIRPORT","STATE","FAAREGION","ENROUTE","RUNWAY","LOCATION","HEIGHT","SPEED","DISTANCE","PHASE_OF_FLT","DAMAGE","STR_RAD","DAM_RAD","STR_WINDSHLD","DAM_WINDSHLD","STR_NOSE","DAM_NOSE","STR_ENG1","DAM_ENG1","STR_ENG2","DAM_ENG2","STR_ENG3","DAM_ENG3","STR_ENG4","DAM_ENG4","INGESTED","STR_PROP","DAM_PROP","STR_WING_ROT","DAM_WING_ROT","STR_FUSE","DAM_FUSE","STR_LG","DAM_LG","STR_TAIL","DAM_TAIL","STR_LGHTS","DAM_LGHTS","STR_OTHER","DAM_OTHER","OTHER_SPECIFY","EFFECT","EFFECT_OTHER","SKY","PRECIP","SPECIES_ID","SPECIES","BIRDS_SEEN","BIRDS_STRUCK","SIZE","WARNED","COMMENTS","REMARKS","AOS","COST_REPAIRS","COST_OTHER","COST_REPAIRS_INFL_ADJ","COST_OTHER_INFL_ADJ","REPORTED_NAME","REPORTED_TITLE","REPORTED_DATE","SOURCE","PERSON","NR_INJURIES","NR_FATALITIES","LUPDATE","TRANSFER","INDICATED_DAMAGE")
#names(srb_1990_Current) <- c("INDEX_NR","OPID","OPERATOR","ATYPE","AMA","AMO","EMA","EMO","AC_CLASS","AC_MASS","NUM_ENGS","TYPE_ENG","ENG_1_POS","ENG_2_POS","ENG_3_POS","ENG_4_POS","REG","FLT","REMAINS_COLLECTED","REMAINS_SENT","INCIDENT_DATE","INCIDENT_MONTH","INCIDENT_YEAR","TIME_OF_DAY","TIME","AIRPORT_ID","AIRPORT","STATE","FAAREGION","ENROUTE","RUNWAY","LOCATION","HEIGHT","SPEED","DISTANCE","PHASE_OF_FLT","DAMAGE","STR_RAD","DAM_RAD","STR_WINDSHLD","DAM_WINDSHLD","STR_NOSE","DAM_NOSE","STR_ENG1","DAM_ENG1","STR_ENG2","DAM_ENG2","STR_ENG3","DAM_ENG3","STR_ENG4","DAM_ENG4","INGESTED","STR_PROP","DAM_PROP","STR_WING_ROT","DAM_WING_ROT","STR_FUSE","DAM_FUSE","STR_LG","DAM_LG","STR_TAIL","DAM_TAIL","STR_LGHTS","DAM_LGHTS","STR_OTHER","DAM_OTHER","OTHER_SPECIFY","EFFECT","EFFECT_OTHER","SKY","PRECIP","SPECIES_ID","SPECIES","BIRDS_SEEN","BIRDS_STRUCK","SIZE","WARNED","COMMENTS","REMARKS","AOS","COST_REPAIRS","COST_OTHER","COST_REPAIRS_INFL_ADJ","COST_OTHER_INFL_ADJ","REPORTED_NAME","REPORTED_TITLE","REPORTED_DATE","SOURCE","PERSON","NR_INJURIES","NR_FATALITIES","LUPDATE","TRANSFER","INDICATED_DAMAGE")
